In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("Advertising.csv")

In [3]:
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [5]:
X = df.drop("sales", axis=1)
y = df["sales"]

In [6]:
from sklearn.preprocessing import PolynomialFeatures

In [7]:
poly_converter = PolynomialFeatures(degree=2, include_bias=False) # bias - это константа

In [9]:
poly_converter.fit(X)

PolynomialFeatures(include_bias=False)

In [21]:
poly_features = poly_converter.transform(X)

In [22]:
poly_features.shape

(200, 9)

In [16]:
poly_features[0]

array([2.301000e+02, 3.780000e+01, 6.920000e+01, 5.294601e+04,
       8.697780e+03, 1.592292e+04, 1.428840e+03, 2.615760e+03,
       4.788640e+03])

In [17]:
pd.DataFrame(poly_features, columns=poly_converter.get_feature_names_out(X.columns))

TV  radio  newspaper      TV^2  TV radio  TV newspaper  radio^2  \
0    230.1   37.8       69.2  52946.01   8697.78      15922.92  1428.84   
1     44.5   39.3       45.1   1980.25   1748.85       2006.95  1544.49   
2     17.2   45.9       69.3    295.84    789.48       1191.96  2106.81   
3    151.5   41.3       58.5  22952.25   6256.95       8862.75  1705.69   
4    180.8   10.8       58.4  32688.64   1952.64      10558.72   116.64   
..     ...    ...        ...       ...       ...           ...      ...   
195   38.2    3.7       13.8   1459.24    141.34        527.16    13.69   
196   94.2    4.9        8.1   8873.64    461.58        763.02    24.01   
197  177.0    9.3        6.4  31329.00   1646.10       1132.80    86.49   
198  283.6   42.0       66.2  80428.96  11911.20      18774.32  1764.00   
199  232.1    8.6        8.7  53870.41   1996.06       2019.27    73.96   

     radio newspaper  newspaper^2  
0            2615.76      4788.64  
1            1772.43      2034.01  
2            3180.87      4802.49  
3            2416.05      3422.25  
4             630.72      3410.56  
..               ...          ...  
195            51.06       190.44  
196            39.69        65.61  
197            59.52        40.96  
198          2780.40      4382.44  
199            74.82        75.69  

[200 rows x 9 columns]

In [18]:
poly_converter.fit_transform(X)

array([[ 230.1 ,   37.8 ,   69.2 , ..., 1428.84, 2615.76, 4788.64],
       [  44.5 ,   39.3 ,   45.1 , ..., 1544.49, 1772.43, 2034.01],
       [  17.2 ,   45.9 ,   69.3 , ..., 2106.81, 3180.87, 4802.49],
       ...,
       [ 177.  ,    9.3 ,    6.4 , ...,   86.49,   59.52,   40.96],
       [ 283.6 ,   42.  ,   66.2 , ..., 1764.  , 2780.4 , 4382.44],
       [ 232.1 ,    8.6 ,    8.7 , ...,   73.96,   74.82,   75.69]])

In [19]:
from sklearn.model_selection import train_test_split

In [23]:
poly_features.shape

(200, 9)

In [24]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

In [26]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [27]:
model.fit(X_train, y_train)

LinearRegression()

In [28]:
test_predictions = model.predict(X_test)

In [30]:
model.coef_

array([ 5.17095811e-02,  1.30848864e-02,  1.20000085e-02, -1.10892474e-04,
        1.14212673e-03, -5.24100082e-05,  3.34919737e-05,  1.46380310e-04,
       -3.04715806e-05])

In [31]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [36]:
MAE = mean_absolute_error(y_test, test_predictions)
print(MAE)

0.4896798044803529


In [35]:
MSE = mean_squared_error(y_test, test_predictions)
RMSE = np.sqrt(MSE)
print(RMSE)

0.664643175726896


In [38]:
pd.DataFrame([model.coef_], columns=poly_converter.get_feature_names_out(X.columns))

TV     radio  newspaper      TV^2  TV radio  TV newspaper   radio^2  \
0  0.05171  0.013085      0.012 -0.000111  0.001142     -0.000052  0.000033   

   radio newspaper  newspaper^2  
0         0.000146     -0.00003